"""db refactor

Revision ID: 061b7ac47035
Revises: 2210678f1df2
Create Date: 2026-04-26 11:31:47.585084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '061b7ac47035'
down_revision: Union[str, Sequence[str], None] = '2210678f1df2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availabilities', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('availabilities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('companies', sa.Column('profile_id', sa.UUID(), nullable=False))
    op.add_column('companies', sa.Column('tagline', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('company_type_id', sa.UUID(), nullable=True))
    op.add_column('companies', sa.Column('offering_tags', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('companies', sa.Column('seeking_tags', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('companies', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('companies', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'BiH'::character varying"))
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('companies_user_id_key'), 'companies', type_='unique')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.create_unique_constraint(None, 'companies', ['profile_id'])
    op.drop_constraint(op.f('companies_user_id_fkey'), 'companies', type_='foreignkey')
    op.create_foreign_key(None, 'companies', 'profiles', ['profile_id'], ['id'])
    op.create_foreign_key(None, 'companies', 'company_types', ['company_type_id'], ['id'])
    op.drop_column('companies', 'address')
    op.drop_column('companies', 'user_id')
    op.drop_column('companies', 'looking_for')
    op.drop_column('companies', 'description')
    op.add_column('industries', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('industries', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('industries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('meeting_requests', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('meeting_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('profile_tags', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('profile_tags', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('profile_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('profiles', sa.Column('position', sa.String(), nullable=False))
    op.add_column('profiles', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('linkedin_url', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('accepting_meetings', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('availability_note', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_column('profiles', 'city')
    op.drop_column('profiles', 'headline')
    op.drop_column('profiles', 'looking_for')
    op.drop_column('profiles', 'country')
    op.drop_column('profiles', 'profile_image_url')
    op.add_column('tags', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('tags', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('unavailable_periods', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('unavailable_periods', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('unavailable_periods', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('user_refresh_tokens', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user_refresh_tokens', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('user_refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'account_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_type', postgresql.ENUM('individual', 'company', name='account_type_enum'), autoincrement=False, nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'deleted_at')
    op.alter_column('user_refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('user_refresh_tokens', 'deleted_at')
    op.drop_column('user_refresh_tokens', 'updated_at')
    op.alter_column('unavailable_periods', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('unavailable_periods', 'deleted_at')
    op.drop_column('unavailable_periods', 'updated_at')
    op.alter_column('tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('tags', 'deleted_at')
    op.drop_column('tags', 'updated_at')
    op.add_column('profiles', sa.Column('profile_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('country', sa.VARCHAR(), server_default=sa.text("'BiH'::character varying"), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('looking_for', postgresql.ENUM('client', 'job', 'partner', 'networking', name='looking_for_enum'), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('headline', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('profiles', 'deleted_at')
    op.drop_column('profiles', 'availability_note')
    op.drop_column('profiles', 'accepting_meetings')
    op.drop_column('profiles', 'linkedin_url')
    op.drop_column('profiles', 'avatar_url')
    op.drop_column('profiles', 'position')
    op.alter_column('profile_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('profile_tags', 'deleted_at')
    op.drop_column('profile_tags', 'updated_at')
    op.alter_column('meeting_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('meeting_requests', 'deleted_at')
    op.alter_column('industries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('industries', 'deleted_at')
    op.drop_column('industries', 'updated_at')
    op.add_column('companies', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('looking_for', postgresql.ENUM('clients', 'partners', 'suppliers', 'talent', 'networking', name='company_looking_for_enum'), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('companies', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.create_foreign_key(op.f('companies_user_id_fkey'), 'companies', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'companies', type_='unique')
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_unique_constraint(op.f('companies_user_id_key'), 'companies', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'BiH'::character varying"))
    op.drop_column('companies', 'deleted_at')
    op.drop_column('companies', 'seeking_tags')
    op.drop_column('companies', 'offering_tags')
    op.drop_column('companies', 'company_type_id')
    op.drop_column('companies', 'tagline')
    op.drop_column('companies', 'profile_id')
    op.alter_column('availabilities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('availabilities', 'deleted_at')
    # ### end Alembic commands ###
